### ISSUE TITLE
HTML Skeleton

### ISSUE THREAD

**Issue by aggicreative555** [aggicreative555/Community-Science-Museum#7]
- [x] !Doctype
- [x] Add header, main and footer to all pages 
- [x] Add basic divs to separate content to all pages
- [x] Add div class names to all pages
- [x] BEM class name method

**Comment by konakallanikhil** [comment]
I can contribute to the project

**Comment by aggicreative555** [comment]
@konakallanikhil 
Hi! Thank you for your suggestion. This is a school project, which I'm tasked to work on alone. Maybe we can collaborate on some future projects. :)

**Comment by konakallanikhil** [comment]
Hi! Thank you for reply.
